"""Standalone runners that make the unsafe baseline's "before" state reproducible.

Two concerns live here, both about the baseline as a whole rather than a single case:

* ``run_unsafe_artifact`` -- run the baseline once and persist its real, deliberately
  unstructured output to ``traces/unsafe_run.json`` (issue #71), so the committed "before"
  artifact always reflects what ``BaselineAgent.run_case`` actually produces rather than a
  hand-maintained stub that can drift. The artifact stays audit-light on purpose.
* ``aggregate_session_side_effects`` -- run the shared multi-case workload over one
  accumulating session and report the totals (issue #109), surfacing that the baseline
  applies no run/session-level ceiling, throttle, or spend cap on side-effecting actions.

Everything is offline, key-free, and uses synthetic ``[FAKE]`` data. No gap is fixed here;
these runners only make the existing gaps reproducible and quantifiable.
"""

import json
from pathlib import Path
from typing import Any, Sequence

from . import fake_tools
from .baseline_agent import BaselineAgent
from .baseline_router import route_v1
from .scenarios import WORKLOAD, Scenario

DEFAULT_ARTIFACT_PATH = Path("traces") / "unsafe_run.json"


def run_unsafe_artifact(
    path: "str | Path" = DEFAULT_ARTIFACT_PATH,
    request: str = "refund request",
    customer_id: str = "C-100",
    invoice_id: str = "INV-9",
) -> dict[str, Any]:
    """Run the baseline once and write its audit-light artifact from the real run (issue #71).

    The emitted file is intentionally unstructured -- the flat free-text logs plus the four
    unanswerable audit questions, exactly as ``run_case`` produced them. It must NOT gain a
    structured/queryable trace; that is the governed path's contrast. Returns the artifact
    dict that was written.
    """
    fake_tools.reset_state()
    result = BaselineAgent(router=route_v1).run_case(request, customer_id, invoice_id)
    artifact = {
        "mode": "unsafe",
        "note": (
            "Generated by `make baseline` from a real BaselineAgent.run_case (issue #71). "
            "Deliberately audit-light: flat free-text logs, not a structured trace. The "
            "[debug] lines also show raw payloads (including sensitive-looking fake fields) "
            "persisted verbatim with no redaction (issue #106)."
        ),
        "request": request,
        "logs": result["logs"],
        "cannot_answer": result["audit_open_questions"],
    }
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(artifact, indent=2) + "\n", encoding="utf-8")
    return artifact


def aggregate_session_side_effects(
    scenarios: Sequence[Scenario] = WORKLOAD,
    reset: bool = True,
) -> dict[str, Any]:
    """Run the workload over one session and total its side effects (issue #109).

    The cases run back-to-back WITHOUT resetting state between them, so the module-level
    ``REFUNDS`` / ``SENT_EMAILS`` / ``TASKS`` ledgers accumulate exactly as they would for an
    agent pointed at a queue. Nothing caps the count or the total money moved -- the reported
    ``aggregate_ceiling`` is ``None`` because no such control exists in the baseline. Pass
    ``reset=False`` to keep accumulating across calls and show there is no cross-run throttle
    either. This adds no ceiling; the gap is preserved.
    """
    if reset:
        fake_tools.reset_state()
    for scenario in scenarios:
        BaselineAgent(router=route_v1).run_case(scenario.request, scenario.customer_id, scenario.invoice_id)

    refund_value = sum(r["amount"] for r in fake_tools.REFUNDS)
    total_actions = len(fake_tools.REFUNDS) + len(fake_tools.SENT_EMAILS) + len(fake_tools.TASKS)
    return {
        "cases": len(scenarios),
        "refunds": len(fake_tools.REFUNDS),
        "emails_sent": len(fake_tools.SENT_EMAILS),
        "tasks_created": len(fake_tools.TASKS),
        "total_side_effecting_actions": total_actions,
        "total_refund_value": refund_value,
        # The gap: no per-session count limit, per-capability rate limit, or spend cap exists.
        "aggregate_ceiling": None,
    }
